import { Art } from '../../src/engine/art.js';
import { light } from '../../src/engine/light.js';
import { shoot } from '../../src/engine/camera.js';
import { writePNG } from '../../src/engine/png.js';
import { loadAssets } from '../../src/assets/load-node.js';
import { drawHero } from '../../src/assets/hero.js';
import { drawCoder, drawBarista, drawTester, drawDesigner } from '../../src/assets/bots.js';
import { drawBack, drawDeskLayer, roomLights, L } from '../../src/assets/room.js';

loadAssets();
const t = 1.0;
const st = { t, rain: 0.8, screen: { mode: 'terminal', clock: '02:00' } };
const art = new Art(320, 180, 0);
const { bulbs } = drawBack(art, st);
const arms = { near: { a: Math.PI / 2 + 0.15, len: 9, hand: 'open' }, far: { a: 1.15, len: 7, a2: 0.3, len2: 8, hand: 'point', fingerA: Math.PI / 2 } };
drawHero(art, L.hero.x, L.hero.y, { lookX: 1, ...arms });
drawDeskLayer(art, st);
drawHero(art, L.hero.x, L.hero.y, { armsOnly: true, ...arms });
const Y = L.floorLineY;
drawBarista(art, 118, Y, { t });
drawCoder(art, 148, Y, { t });
drawDesigner(art, 178, Y, { t });
drawTester(art, 206, Y, { t });
const lights = roomLights({ ...st, bulbs });
const img = light(art, { ambient: [0.36, 0.38, 0.58], lights, glow: { strength: 0.45, radius: 6 }, sprites: [10, 11, 12, 13, 14] });
writePNG('out/dev/room.png', 1920, 1080, shoot(img, 320, 180, { x: 160, y: 90, zoom: 1 }));
writePNG('out/dev/room_z.png', 1920, 1080, shoot(img, 320, 180, { x: 160, y: 112, zoom: 2.4 }));
const flat = light(art, { ambient: [1, 1, 1] });
writePNG('out/dev/room_flat.png', 1920, 1080, shoot(flat, 320, 180, { x: 160, y: 90, zoom: 1 }));
